[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]
  external_node_modules = ["axios", "openai"]

[functions."generate-story"]
  timeout = 60

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
